#!/usr/bin/env bash
BASE_DIR="$(realpath "$(dirname "$0")")"
OUTPUT_DIR=~/syncthing/Musica-noobi
LOGFILE=$(basename "$0" .py).$(date -Is).log
if which pluma >/dev/null
then
    EDITOR=pluma
else
    EDITOR=gedit
fi


SOUND_URLS_FILE=$(tempfile --suffix .txt) || exit
trap 'rm -f -- "$SOUND_URLS_FILE"' EXIT


"$EDITOR" "$SOUND_URLS_FILE"

cd "$BASE_DIR"
exec > "$LOGFILE" 2>&1
cat "$SOUND_URLS_FILE"

pipenv install youtube-dl
pipenv update
pipenv run youtube-dl \
    --update \
    --extract-audio \
    --format m4a \
    --batch-file "$SOUND_URLS_FILE" \
    -o "$OUTPUT_DIR/%(title)s-%(id)s.%(ext)s" \
    --verbose

xdg-open "$OUTPUT_DIR"
if syncthing &
then
  sleep 10
  xdg-open "http://127.0.0.1:8384/"
fi
